name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger pipeline on push to 'master' branch
  pull_request:
    branches:
      - master  # Trigger pipeline on pull request to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Set Python version to 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q  # Run tests with pytest

  docker:
    runs-on: ubuntu-latest
    needs: build  # Only run this job if the build job is successful

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-fastapi-app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag my-fastapi-app kapilsolanki2808/my-fastapi-app:latest
        docker push kapilsolanki2808/my-fastapi-app:latest

  # The 'deploy' job is removed because you're deploying locally, not on a server
